export class Artigo {
    id: number = 0;
    trilha: string = '';
    titulo: string = '';
    texto1: string = '';
    img1: string = '';
    texto2: string = '';
    img2: string = '';
    mp: string = '';
    iconTexto: string = '';
    tituloTexto: string = '';
    descricaoTexto: string = '';
    iconYoutube: string = '';
    tituloYoutube: string = '';
    descricaoYoutube: string = '';
    iconPodcast: string = '';
    tituloPodcast: string = '';
    descricaoPodcast: string = '';
    iconFilme: string = '';
    tituloFilme: string = '';
    descricaoFilme: string = '';
}